const fs = require('fs');
const path = require('path');

const localeDir = path.join(process.cwd(), 'src', 'locales');

const newKeys = {
  ko: { start_premium: "🔓 Premium 시작하기 — $4.99/월", cancel_anytime: "언제든지 해지 가능 · 7일 무료 체험", identification_basis: "품종 식별 근거", source_label: "출처", wsava_default: "영양 상태는 체온, 맥박과 함께 \"다섯 번째 활력징후\"입니다. 체계적인 영양 평가를 통해 질병을 예방하고 수명을 연장할 수 있습니다.", wsava_source: "출처: 세계소동물수의사회 (WSAVA) 지침", stevemann_default: "강압적인 방식 대신 간식과 장난감을 활용한 \"긍정강화교육\"이 반려견과의 신뢰를 쌓는 핵심입니다. 보디랭귀지를 이해하고 소통하세요.", stevemann_source: "출처: 스티브 만 (Steve Mann) 교육 방법론", lineage_retriever: "리트리버 계열 (Retriever Lineage)", lineage_spitz: "스피츠 계열 (Spitz Lineage)", lineage_others: "기타 미분류 (Others)", default_risk_name: "고관절 이형성증", default_risk_desc: "골든 리트리버 품종에서 흔히 발생합니다. 관절 건강을 위해 조기 발견과 체중 관리가 매우 중요합니다.", premium_desc_connector: "및", premium_desc_suffix: "입니다.", marker_mdr1: "MDR1 유전자 변이", marker_dm: "퇴행성 골수염 (DM)", marker_pra: "진행성 망막 위축증", default_disclaimer: "이 분석은 AI 시각 평가와 공개된 수의학 연구를 기반으로 합니다. 전문 수의사의 진단을 대체하지 않습니다.", references_title: "참고 자료 References", risk_level_high: "위험", risk_level_medium: "주의", risk_level_low: "양호" },
  en: { start_premium: "🔓 Start Premium — $4.99/mo", cancel_anytime: "Cancel anytime · 7-day free trial", identification_basis: "Identification Basis", source_label: "Source", wsava_default: "Nutritional status is the \"fifth vital sign\" alongside temperature and pulse. Systematic nutritional assessment can prevent disease and extend lifespan.", wsava_source: "Source: World Small Animal Veterinary Association (WSAVA) Guidelines", stevemann_default: "Instead of coercive methods, \"positive reinforcement training\" using treats and toys is key to building trust with your dog. Understand their body language and communicate.", stevemann_source: "Source: Steve Mann Training Methodology", lineage_retriever: "Retriever Lineage", lineage_spitz: "Spitz Lineage", lineage_others: "Others", default_risk_name: "Hip Dysplasia", default_risk_desc: "Commonly found in Golden Retriever breeds. Early detection and weight management are critical for joint health.", premium_desc_connector: "and", premium_desc_suffix: ".", marker_mdr1: "MDR1 Gene Mutation", marker_dm: "Degenerative Myelopathy (DM)", marker_pra: "Progressive Retinal Atrophy", default_disclaimer: "This analysis is based on AI visual assessment and published veterinary research. It does not replace professional veterinary diagnosis.", references_title: "References", risk_level_high: "Critical", risk_level_medium: "Moderate", risk_level_low: "Normal" },
  ja: { start_premium: "🔓 Premiumを開始 — $4.99/月", cancel_anytime: "いつでもキャンセル可能・7日間無料体験", identification_basis: "品種識別根拠", source_label: "出典", wsava_default: "栄養状態は体温、脈拍と並ぶ「5番目のバイタルサイン」です。体系的な栄養評価により疾病を予防し寿命を延ばすことができます。", wsava_source: "出典：世界小動物獣医師会（WSAVA）ガイドライン", stevemann_default: "強圧的な方法の代わりに、おやつやおもちゃを活用した「正の強化トレーニング」が愛犬との信頼関係を築く鍵です。ボディランゲージを理解し、コミュニケーションを取りましょう。", stevemann_source: "出典：スティーブ・マン（Steve Mann）教育方法論", lineage_retriever: "レトリーバー系統", lineage_spitz: "スピッツ系統", lineage_others: "その他", default_risk_name: "股関節形成不全", default_risk_desc: "ゴールデンレトリーバーによく見られる疾患です。関節の健康のために早期発見と体重管理が非常に重要です。", premium_desc_connector: "と", premium_desc_suffix: "です。", marker_mdr1: "MDR1遺伝子変異", marker_dm: "変性性脊髄症（DM）", marker_pra: "進行性網膜萎縮症", default_disclaimer: "この分析はAIの視覚的評価と公開された獣医学研究に基づいています。専門の獣医師の診断に代わるものではありません。", references_title: "参考文献 References", risk_level_high: "危険", risk_level_medium: "注意", risk_level_low: "良好" },
  zh: { start_premium: "🔓 开始 Premium — $4.99/月", cancel_anytime: "随时取消 · 7天免费试用", identification_basis: "品种识别依据", source_label: "来源", wsava_default: "营养状况与体温、脉搏一样是"第五生命体征"。系统的营养评估可以预防疾病并延长寿命。", wsava_source: "来源：世界小动物兽医协会（WSAVA）指南", stevemann_default: "代替强制方法，利用零食和玩具的"正向强化训练"是与爱犬建立信任的关键。了解它们的肢体语言并进行沟通。", stevemann_source: "来源：Steve Mann 教育方法论", lineage_retriever: "寻回犬系", lineage_spitz: "尖嘴犬系", lineage_others: "其他", default_risk_name: "髋关节发育不良", default_risk_desc: "常见于金毛猎犬品种。早期发现和体重管理对关节健康至关重要。", premium_desc_connector: "和", premium_desc_suffix: "。", marker_mdr1: "MDR1基因突变", marker_dm: "退行性脊髓病（DM）", marker_pra: "进行性视网膜萎缩", default_disclaimer: "本分析基于AI视觉评估和已发表的兽医学研究。不能替代专业兽医的诊断。", references_title: "参考文献 References", risk_level_high: "危险", risk_level_medium: "注意", risk_level_low: "良好" },
  es: { start_premium: "🔓 Iniciar Premium — $4.99/mes", cancel_anytime: "Cancela en cualquier momento · 7 días gratis", identification_basis: "Base de identificación", source_label: "Fuente", wsava_default: "El estado nutricional es el \"quinto signo vital\" junto con la temperatura y el pulso. La evaluación nutricional sistemática puede prevenir enfermedades y prolongar la vida.", wsava_source: "Fuente: Directrices de WSAVA", stevemann_default: "En lugar de métodos coercitivos, el \"entrenamiento de refuerzo positivo\" usando premios y juguetes es clave para construir confianza con tu perro. Comprende su lenguaje corporal y comunícate.", stevemann_source: "Fuente: Metodología de Steve Mann", lineage_retriever: "Linaje Retriever", lineage_spitz: "Linaje Spitz", lineage_others: "Otros", default_risk_name: "Displasia de cadera", default_risk_desc: "Comúnmente encontrada en Golden Retrievers. La detección temprana y el control de peso son fundamentales para la salud articular.", premium_desc_connector: "y", premium_desc_suffix: ".", marker_mdr1: "Mutación del gen MDR1", marker_dm: "Mielopatía degenerativa (DM)", marker_pra: "Atrofia progresiva de retina", default_disclaimer: "Este análisis se basa en la evaluación visual de IA y la investigación veterinaria publicada. No reemplaza el diagnóstico veterinario profesional.", references_title: "Referencias", risk_level_high: "Crítico", risk_level_medium: "Moderado", risk_level_low: "Normal" }
};

for (const [lang, keys] of Object.entries(newKeys)) {
  const fp = path.join(localeDir, lang + '.json');
  const data = JSON.parse(fs.readFileSync(fp, 'utf-8'));
  if (!data.report) data.report = {};
  Object.assign(data.report, keys);
  fs.writeFileSync(fp, JSON.stringify(data, null, 2) + '\n', 'utf-8');
  console.log('Updated ' + lang + '.json');
}
console.log('Done!');
